### ISSUE TITLE
[FEATURE] Database Schema Versioning

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#122]
**Description.**
Ensure the data model with updates in the source code matches the database schema. 
See [JPA Buddy Database Versioning](https://jpa-buddy.com/documentation/database-versioning/) for pointers to solutions.

**Desired functionality acceptance criteria**
Updates to the database schema need to be versioned and automatically applied during a deployment.

**Comment by RadovanTomik** [comment]
done
