### ISSUE TITLE
[FEATURE] Move filtering and sorting capability to the backend

### ISSUE THREAD

**Issue by RadovanTomik** [BBMRI-ERIC/negotiator#130]
**Brief description.**
All filtering and sorting should be done in the backend.

**Desired functionality acceptance criteria**
Client can sort and filter resources,e.g. https://www.atatus.com/blog/rest-api-design-filtering-sorting-and-pagination/

**Comment by svituz** [comment]
closed in [PR 208](https://github.com/BBMRI-ERIC/negotiator/pull/208)
