### ISSUE TITLE
[FEATURE] Add help page

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#165]
**Brief description.**
Add a button or link in the header to reach the help.

**Desired functionality acceptance criteria**
At the moment the link to the help (EMail) is located in the footer

![Help-Footer](https://github.com/BBMRI-ERIC/negotiator-v3/assets/110096044/df153fc4-ce56-45f1-90e5-0aa7fbe6cd70)

This should in some way added to the header, so new users do find an easy way to contact support - see example below:

![Image](https://github.com/BBMRI-ERIC/negotiator-v3/assets/110096044/9907e149-c6e3-4ee9-bae5-7833087671e1)

**Comment by RadovanTomik** [comment]
Changed to add a whole help page with FAQ, guides and contact information.

**Comment by RadovanTomik** [comment]
wrong repo
