### ISSUE TITLE
[V2] Updates of authorization for person mapping to collections deletes historical link data

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#176]
Verification required - issue still open in V2:

When the links of a person to collections are updated in Perun this is propageted to the Negotiator.

The update on the Negotiator is done by deleting all mappings from a person to collections and inserting the mappings again, see:

This should keep previous mappings in some way to allow for auditing when the authorization for a person to collections changed.

**Comment by RadovanTomik** [comment]
present in v3
