### ISSUE TITLE
[FEATURE] Expand biobanker request list to include requests with abandoned state

### ISSUE THREAD

**Issue by jungwire** [BBMRI-ERIC/negotiator#204]
**Brief description.**
The current functionality for fetching requests for biobankers only includes those with the state: "IN_PROGRESS". This feature request proposes an enhancement to the system to include requests with the state: "ABANDONED" alongside the existing "IN_PROGRESS" requests in the data retrieved for biobankers.

**Desired functionality acceptance criteria**
The updated functionality should ensure that the retrieved data for biobankers includes information for both "IN_PROGRESS" and "ABANDONED" requests.

**Comment by RadovanTomik** [comment]
done
