### ISSUE TITLE
[BUG] when the latest docker image of postgres is not present in the host machine, the first one is used

### ISSUE THREAD

**Issue by svituz** [BBMRI-ERIC/negotiator#206]
**Describe the bug**
It seems that if the host machine doesn't have postgres:latest image the minor version in the system is used and this can lead to failure in running the development

**How to reproduce**
pull docker image postgres:9.6.12 and remove the latest tag from the machine you are developing the negotiator
then run the negotiatior.

**What happens**
The negotiator fails because version 9.6.12 is not supported by the adopted version of flyway

**What should happen**
The negotiator should run

**NOTE**
Probably the best solution should be to force the same version used in production

**Comment by RadovanTomik** [comment]
fixed
