### ISSUE TITLE
[FEATURE] Add display of versions for frontend and backend to frontpage

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#224]
**Brief description.**
Add the version of the frontend and backend to the frontpage to be displayed.
This is of great help for Negotiator instances deployed at other infrastructures where we do not have control, but with this can easily verify the deployed versions.

**Desired functionality acceptance criteria**
The versions of both the frontend and the backend should be displayed on the frontpage. Preferred in the footer, where this is not very intrusive but can easily be found.
See the attached image for the location, either at point 1 or at point 2.

![Image](https://github.com/BBMRI-ERIC/negotiator/assets/110096044/90c44012-d73a-47dc-b3fc-c3f9fbcb95fc)

**Comment by RadovanTomik** [comment]
Add git version information to /info endpoint
