### ISSUE TITLE
[FEATURE] Add notification icon to status bar

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#246]
**Brief description.**
The user should see a quick update on changes in requests on the status bar.

**Desired functionality acceptance criteria**
The status bar should display a simple notification if some updates to requests happen.
When clicked on the displayed notification icon a list of changes should be displayed. See the attached screenshot for an example.

![Image](https://github.com/BBMRI-ERIC/negotiator/assets/110096044/5955567e-7d6d-4de5-a14e-c475f42d9316)

**Comment by RadovanTomik** [comment]
wrong repository
