### ISSUE TITLE
[FEATURE] Improve performance when getting negotiations

### ISSUE THREAD

**Issue by svituz** [BBMRI-ERIC/negotiator#248]
**Brief description.**
Currently, the endpoints to get Negotiations return all the attributes of the Negotiations and this can result in lots of information and data returned from the server. Performance may increase drastically by limiting the attributes returned, to the ones actually needed.
Probably, the best is to let the client decide what version of the response it wants (minimal or all). In this way, the frontend can ask only for the minimal set of attributes, while another client can get all.

tasks:

- [x] Adapt the DTO and API endpoints to REST 
- [x] Separate lifecycle history (add an href link for fetching the lifecycle history separately)
- [x] Add links for new states for negotiation state machine
- [x] Add links for new states for resource state machine

**Comment by RadovanTomik** [comment]
done
