### ISSUE TITLE
[FEATURE] Add support for networks

### ISSUE THREAD

**Issue by RadovanTomik** [BBMRI-ERIC/negotiator#253]
**Brief description.**
Add support for networks.

**Desired functionality acceptance criteria**
Has the following attributes:

- [ ] URI/That resolves to a link
- [ ] Name
- [ ] External id
- [ ] Contact email
- [ ] `Set<Person> managers`
- [ ] `Set<Organization> members;`

**Comment by erfannvb** [comment]
Hello @RadovanTomik. I was checking the project and I kind of liked it. I am a new Spring Boot developer. I'd be glad if I could help with contributing to this project.

**Comment by RadovanTomik** [comment]
Hi, sure all contributions are appreciated. Feel free to fork the project, pick an issue and open a PR.
