### ISSUE TITLE
[FEATURE] Additional data types for access form

### ISSUE THREAD

**Issue by konradlang** [BBMRI-ERIC/negotiator#293]
**Brief description.**
For the access form additional data types should be added:

Simple types:
checkbox
text field (with length limitations)
radio button
date

Complex types, where the data to be displayed can be dynamic:
dropdown - dynamic content
menu - dynamic content 

**Desired functionality acceptance criteria**
Additional data types are available and can be used to setup the access form.

**Comment by RadovanTomik** [comment]
```
SINGLE_CHOICE,
  MULTIPLE_CHOICE,
  FILE,
  TEXT,
  TEXT_LARGE,
  BOOLEAN,
  DATE,
  NUMBER,
  INFORMATION
```

**Comment by konradlang** [comment]
> ```
> SINGLE_CHOICE,
>   MULTIPLE_CHOICE,
>   FILE,
>   TEXT,
>   TEXT_LARGE,
>   BOOLEAN,
>   DATE,
>   NUMBER,
>   INFORMATION
> ```

For TEXT and TEXT_LARGE if possible this should include the maximum length in number of characters.
