### ISSUE TITLE
[FEATURE] UI configuration

### ISSUE THREAD

**Issue by RadovanTomik** [BBMRI-ERIC/negotiator#361]
**Brief description.**
Add a REST API endpoint for fetching and updating global UI configuration. For a list of all relevant values contact @tmilost. The update operations should be alowed only for admins. Example response:
 ```
{
"primary-color": "red",
"auth_link": "https://wahever.com"
"logo_url": "https://wahever.com/icon.svg"
}

```
**Desired functionality acceptance criteria**

- [ ] GET `/ui-config`
- [ ] PATCH `/ui-config {"key": "new_value"}`

**Comment by tmilost** [comment]
current values: 
`activeThemeFile: "bbmri",
  activeLogosFiles: "bbmri",
  isFooterStatusPageVisible: true,
  footerStatusPageLink: "https://status.bbmri-eric.eu/",
  footerStatusPageText: "BBMRI-ERIC Status Page",
  isFooterFollowUsVisible: true,
  footerFollowUsLinkedin: "https://www.linkedin.com/company/bbmri-eric",
  footerFollowUsX: "https://twitter.com/BBMRIERIC",
  footerFollowUsPodcast: "https://www.bbmri-eric.eu/bbmri-eric/bbmri-eric-podcast/",
  isFooterWorkProgrammeVisible: true,
  footerWorkProgrammeLink: "https://www.bbmri-eric.eu/wp-content/uploads/BBMRI-ERIC_work-program_2022-2024_DIGITAL.pdf",
  isFooterPrivacyPolicyVisible: true,
  footerPrivacyPolicy: "https://www.bbmri-eric.eu/wp-content/uploads/AoM_10_8_Access-Policy_FINAL_EU.pdf",
  isFooterHelpLinkVisible: true,
  footerHelpLink: "mailto:negotiator@helpdesk.bbmri-eric.eu",
  isFooterCopyRightVisible: true,
  footerCopyRight: "© 2024 BBMRI-ERIC",
  isFooterLeftSideIconVisible: true,
  footerLeftSideIcon: "@/assets/images/bbmri/home-bbmri-png",
  footerLeftSideIconLink: "https://www.bbmri-eric.eu/",
  isFooterNewsletterVisible: true,
  footerNewsletter: "https://www.bbmri-eric.eu/news-event/"`
